<a href="https://colab.research.google.com/github/manoghnagobbilla24/NLP-/blob/main/4078__nlp_6_3_ass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df = pd.read_csv('/content/arxiv_data.csv')

print("First 5 rows of the DataFrame:")
print(df.head())

print("\nColumn names of the DataFrame:")
print(df.columns)

First 5 rows of the DataFrame:
                                              titles  \
0  Survey on Semantic Stereo Matching / Semantic ...
1  FUTURE-AI: Guiding Principles and Consensus Re...
2  Enforcing Mutual Consistency of Hard Regions f...
3  Parameter Decoupling Strategy for Semi-supervi...
4  Background-Foreground Segmentation for Interio...

                                           summaries  \
0  Stereo matching is one of the widely used tech...
1  The recent advancements in artificial intellig...
2  In this paper, we proposed a novel mutual cons...
3  Consistency training has proven to be an advan...
4  To ensure safety in automated driving, the cor...

                         terms
0           ['cs.CV', 'cs.LG']
1  ['cs.CV', 'cs.AI', 'cs.LG']
2           ['cs.CV', 'cs.AI']
3                    ['cs.CV']
4           ['cs.CV', 'cs.LG']

Column names of the DataFrame:
Index(['titles', 'summaries', 'terms'], dtype='object')

In [ ]:
text_data = df['summaries']

print("First 5 entries of the text data:")
print(text_data.head())

print("\nNumber of missing values in text data:")
print(text_data.isnull().sum())

First 5 entries of the text data:
0    Stereo matching is one of the widely used tech...
1    The recent advancements in artificial intellig...
2    In this paper, we proposed a novel mutual cons...
3    Consistency training has proven to be an advan...
4    To ensure safety in automated driving, the cor...
Name: summaries, dtype: object

Number of missing values in text data:
0

In [ ]:
import sys
!{sys.executable} -m pip install nltk
print("nltk installed.")

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.1)
nltk installed.

In [ ]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
nltk.download('wordnet')

# Initialize the WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

# Create a list of English stopwords
stop_words = set(stopwords.words('english'))

def preprocess_text(text):
    # a. Convert the text to lowercase
    text = text.lower()
    # b. Remove non-alphabetic characters
    text = re.sub(r'[^a-z]', ' ', text)
    # c. Tokenize the text into individual words
    words = text.split()
    # d. Remove stopwords from the tokenized words
    words = [word for word in words if word not in stop_words]
    # e. Lemmatize the remaining words
    words = [lemmatizer.lemmatize(word) for word in words]
    # f. Join the processed words back into a single string
    return ' '.join(words)

# Apply this preprocessing function to the text_data Series
cleaned_text = text_data.apply(preprocess_text)

# Print the first 5 entries of the cleaned_text
print("First 5 entries of the cleaned text:")
print(cleaned_text.head())

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

First 5 entries of the cleaned text:
0    stereo matching one widely used technique infe...
1    recent advancement artificial intelligence ai ...
2    paper proposed novel mutual consistency networ...
3    consistency training proven advanced semi supe...
4    ensure safety automated driving correct percep...
Name: summaries, dtype: object

In [ ]:
 # Step 1: Import CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer

# Assume cleaned_text is a list of preprocessed text documents
# Example: cleaned_text = ["this is a sample document", "this document is another example"]

# Step 2: Initialize CountVectorizer with parameters
vectorizer = CountVectorizer(max_df=0.9, min_df=5)

# Step 3: Fit and transform the cleaned_text data
bow_matrix = vectorizer.fit_transform(cleaned_text)

# Step 4: Print shape and first 10 feature names
print("Shape of BoW matrix:", bow_matrix.shape)
print("First 10 feature names:", vectorizer.get_feature_names_out()[:10])

Shape of BoW matrix: (51774, 15424)
First 10 feature names: ['aa' 'aaai' 'aachen' 'aae' 'aaf' 'aam' 'aan' 'ab' 'abandon' 'abaw']

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

# Initialize CountVectorizer with specified parameters
# max_df=0.9 ignores terms that appear in more than 90% of the documents
# min_df=5 ignores terms that appear in less than 5 documents
vectorizer = CountVectorizer(max_df=0.9, min_df=5)

# Fit and transform the cleaned_text data to create the Bag of Words matrix
bow_matrix = vectorizer.fit_transform(cleaned_text)

# Print the shape of the resulting BoW matrix
print("Shape of Bag of Words matrix:", bow_matrix.shape)

# Get the feature names (words)
feature_names = vectorizer.get_feature_names_out()

# Print the first 10 feature names
print("First 10 feature names:", feature_names[:10])

Shape of Bag of Words matrix: (51774, 15424)
First 10 feature names: ['aa' 'aaai' 'aachen' 'aae' 'aaf' 'aam' 'aan' 'ab' 'abandon' 'abaw']

In [ ]:
from sklearn.decomposition import LatentDirichletAllocation

def display_topics(model, feature_names, no_top_words):
    for topic_idx, topic in enumerate(model.components_):
        print(f"Topic {topic_idx + 1}:")
        # Get indices of words with highest probabilities for this topic
        top_words_indices = topic.argsort()[:-no_top_words - 1:-1]
        # Get the actual words using the indices
        top_words = [feature_names[i] for i in top_words_indices]
        print(f"  {', '.join(top_words)}")

# Initialize LDA model
lda_model = LatentDirichletAllocation(n_components=5, random_state=42) # You can adjust n_components

# Fit LDA model to the bow_matrix (from arxiv_data.csv as per prior steps)
lda_model.fit(bow_matrix)

# Display the top 10 words for each topic
display_topics(lda_model, feature_names, 10)

Topic 1:
  aaf, aa, aaai, abbr, abbreviated, abbreviate, abandon, aachen, ab, abaw
Topic 2:
  abbreviated, abbr, aaai, abandon, abbreviate, aachen, aaf, aa, ab, abaw
Topic 3:
  abbreviated, abbr, aaai, abandon, abbreviate, aachen, aaf, aa, ab, abaw
Topic 4:
  abaw, aam, aae, aan, abandon, abbreviate, aachen, abbr, abbreviated, aaai
Topic 5:
  ab, abandon, abbreviate, aachen, abbreviated, aaai, abbr, aa, aaf, abaw

In [ ]:
import numpy as np

# Transform the bow_matrix using the fitted lda_model to get document-topic distributions
document_topic_distributions = lda_model.transform(bow_matrix)

# Print the shape of the document-topic distributions
print("Shape of document-topic distributions:", document_topic_distributions.shape)

Shape of document-topic distributions: (4, 5)

In [ ]:
import numpy as np

# Identify the dominant topic for each document
# np.argmax finds the index of the maximum probability along axis=1 (for each row/document)
dominant_topics = np.argmax(document_topic_distributions, axis=1)

# Add the 'dominant_topic' column to the original DataFrame df
df['dominant_topic'] = dominant_topics

# Display the first few rows of the updated DataFrame with the new column
print("First 5 rows of the DataFrame with 'dominant_topic' column:")
print(df.head())

First 5 rows of the DataFrame with 'dominant_topic' column:
   Category                              News  \
0    Sports     Virat scored century in match
1  Politics              BJP won in elections
2    Sports  Bumrah took 5 wickets in a match
3  Politics  Congress formed state government

                         clean_text  dominant_topic
0        virat scored century match               4
1                      bjp election               0
2          bumrah took wicket match               4
3  congress formed state government               3

In [ ]:
import pandas as pd

# Load dataset
df = pd.read_csv("/content/news.csv") # Corrected file path

# Select text column
texts = df['News'].astype(str) # Corrected column name to 'News'

print(texts.head())

0       Virat scored century in match
1                BJP won in elections
2    Bumrah took 5 wickets in a match
3    Congress formed state government
Name: News, dtype: object

In [ ]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess(text):
    # Lowercase
    text = text.lower()

    # Remove special characters & numbers
    text = re.sub(r'[^a-z\s]', '', text)

    # Tokenization
    tokens = text.split()

    # Stopword removal & lemmatization
    tokens = [lemmatizer.lemmatize(word)
              for word in tokens if word not in stop_words]

    # Rejoin
    return ' '.join(tokens)

df['clean_text'] = texts.apply(preprocess)

print(df['clean_text'].head())

0          virat scored century match
1                        bjp election
2            bumrah took wicket match
3    congress formed state government
Name: clean_text, dtype: object

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
bow = vectorizer.fit_transform(df['clean_text'])

In [ ]:
bow_df = pd.DataFrame(
    bow.toarray(),
    columns=vectorizer.get_feature_names_out()
)

print(bow_df.head())

   bjp  bumrah  century  congress  election  formed  government  match  \
0    0       0        1         0         0       0           0      1
1    1       0        0         0         1       0           0      0
2    0       1        0         0         0       0           0      1
3    0       0        0         1         0       1           1      0

   scored  state  took  virat  wicket
0       1      0     0      1       0
1       0      0     0      0       0
2       0      0     1      0       1
3       0      1     0      0       0

In [ ]:
from sklearn.decomposition import LatentDirichletAllocation

lda = LatentDirichletAllocation(
    n_components=2,      # number of topics
    random_state=42
)

lda.fit(bow)

LatentDirichletAllocation(n_components=2, random_state=42)

In [ ]:
def display_topics(model, feature_names, no_top_words):
    for topic_idx, topic in enumerate(model.components_):
        print(f"\nTopic {topic_idx + 1}:")
        print(" ".join([
            feature_names[i]
            for i in topic.argsort()[:-no_top_words - 1:-1]
        ]))

display_topics(lda, vectorizer.get_feature_names_out(), 5)

Topic 1:
formed government congress state election

Topic 2:
match virat century scored took

In [ ]:
topic_values = lda.transform(bow)
df['topic'] = topic_values.argmax(axis=1)

print(df[['News', 'topic']])

                               News  topic
0     Virat scored century in match      1
1              BJP won in elections      0
2  Bumrah took 5 wickets in a match      1
3  Congress formed state government      0

NMF

In [ ]:
import pandas as pd
import re
import nltk

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import NMF

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [ ]:
import pandas as pd

df = pd.read_csv('/content/arxiv_data.csv', engine='python', on_bad_lines='warn')
texts = df['summaries'].astype(str)

In [ ]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
nltk.download('wordnet')

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess(text):
    text = text.lower()
    text = re.sub(r'[^a-z\s]', '', text)
    tokens = text.split()
    tokens = [lemmatizer.lemmatize(w) for w in tokens if w not in stop_words]
    return " ".join(tokens)

df['clean_text'] = texts.apply(preprocess)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(max_features=1000)
bow_matrix = vectorizer.fit_transform(df['clean_text'])

In [ ]:
bow_df = pd.DataFrame(
    bow_matrix.toarray(),
    columns=vectorizer.get_feature_names_out()
)

bow_df.head()

,bjp,bumrah,century,congress,election,formed,government,match,scored,state,took,virat,wicket
0,0,0,1,0,0,0,0,1,1,0,0,1,0
1,1,0,0,0,1,0,0,0,0,0,0,0,0
2,0,1,0,0,0,0,0,1,0,0,1,0,1
3,0,0,0,1,0,1,1,0,0,1,0,0,0

In [ ]:
from sklearn.decomposition import NMF

nmf_model = NMF(
    n_components=5,
    random_state=42
)

W = nmf_model.fit_transform(bow_matrix)
H = nmf_model.components_

In [ ]:
words = vectorizer.get_feature_names_out()

for topic_idx, topic in enumerate(H):
    print(f"\nTopic {topic_idx + 1}:")
    print([words[i] for i in topic.argsort()[-10:]])

Topic 1:
['election', 'match', 'virat', 'took', 'scored', 'wicket', 'formed', 'state', 'congress', 'government']

Topic 2:
['election', 'government', 'formed', 'state', 'scored', 'virat', 'bumrah', 'wicket', 'took', 'match']

Topic 3:
['election', 'government', 'formed', 'took', 'state', 'wicket', 'match', 'century', 'scored', 'virat']

Topic 4:
['election', 'virat', 'scored', 'bumrah', 'took', 'wicket', 'congress', 'government', 'state', 'formed']

Topic 5:
['formed', 'match', 'government', 'state', 'scored', 'wicket', 'virat', 'took', 'bjp', 'election']

In [ ]:
df['Topic'] = W.argmax(axis=1)
df[['News', 'Topic']].head()

                               News  Topic
0     Virat scored century in match      2
1              BJP won in elections      4
2  Bumrah took 5 wickets in a match      1
3  Congress formed state government      0

In [ ]:
import pandas as pd

df = pd.read_csv('/content/news.csv')
texts = df['News'].astype(str)

In [ ]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
nltk.download('wordnet')

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess(text):
    text = text.lower()
    text = re.sub(r'[^a-z\s]', '', text)
    tokens = text.split()
    tokens = [lemmatizer.lemmatize(w) for w in tokens if w not in stop_words]
    return " ".join(tokens)

df['clean_text'] = texts.apply(preprocess)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

# Ensure 'clean_text' is available in the current DataFrame
# The 'texts' variable and 'preprocess' function should be available from previous successful executions.
df['clean_text'] = texts.apply(preprocess)

vectorizer = CountVectorizer(max_features=1000)
bow_matrix = vectorizer.fit_transform(df['clean_text'])

In [ ]:
bow_df = pd.DataFrame(
    bow_matrix.toarray(),
    columns=vectorizer.get_feature_names_out()
)

bow_df.head()

,aa,aaai,aachen,aae,aaf,aam,aan,ab,abandon,abaw,...,zo,zone,zoo,zoom,zoomed,zooming,zsd,zsl,zurich,zynq
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# Apply NMF
from sklearn.decomposition import NMF
import numpy as np

nmf_model = NMF(n_components=5, random_state=42)

W = nmf_model.fit_transform(bow_matrix)   # Document–Topic matrix
H = nmf_model.components_                # Topic–Word matrix

# ---- OUTPUTS ----

# 1. Model
print("NMF Model:")
print(nmf_model)

# 2. Shape of W
print("\nShape of W (Documents × Topics):")
print(W.shape)

# 3. Shape of H
print("\nShape of H (Topics × Words):")
print(H.shape)

# 4. Sample values of W
print("\nSample W values (first 3 documents):")
print(W[:3])

# 5. Sample values of H
print("\nSample H values (first topic, first 10 words):")
print(H[0][:10])

# 6. Dominant topic for each document
dominant_topics = np.argmax(W, axis=1)
print("\nDominant topics (first 10 documents):")
print(dominant_topics[:10])

NMF Model:
NMF(n_components=5, random_state=42)

Shape of W (Documents × Topics):
(51774, 5)

Shape of H (Topics × Words):
(5, 15424)

Sample W values (first 3 documents):
[[0.0045633  0.10329528 0.01984679 0.01823227 0.09188197]
 [0.03065089 0.13889432 0.         0.02041845 0.        ]
 [0.01763693 0.16786187 0.         0.39874018 0.0978476 ]]

Sample H values (first topic, first 10 words):
[0.00074869 0.00058845 0.00016638 0.00146081 0.         0.
 0.         0.00374778 0.00099268 0.        ]

Dominant topics (first 10 documents):
[1 1 3 3 4 4 4 0 0 1]

In [ ]:
feature_names = vectorizer.get_feature_names_out()

for topic_idx, topic in enumerate(H):
    print(f"\nTopic {topic_idx + 1}:")
    print([feature_names[i] for i in topic.argsort()[-10:]])

Topic 1:
['aaf', 'ab', 'abbreviate', 'abbr', 'abandon', 'abbreviated', 'aam', 'abaw', 'aae', 'aan']

Topic 2:
['aaf', 'aan', 'aam', 'abaw', 'abandon', 'abbreviate', 'aaai', 'abbreviated', 'abbr', 'ab']

Topic 3:
['aaf', 'aan', 'aam', 'abbr', 'abaw', 'abbreviated', 'ab', 'aachen', 'abandon', 'abbreviate']

Topic 4:
['aaf', 'abbreviate', 'abandon', 'aaai', 'abbr', 'abbreviated', 'aae', 'aan', 'abaw', 'aam']

Topic 5:
['aam', 'ab', 'aan', 'abaw', 'abandon', 'abbreviated', 'abbreviate', 'abbr', 'aa', 'aaf']

In [ ]:
# The error indicates a mismatch in the number of rows between 'df' and 'W'.
# 'W' was generated from the 'news.csv' data (4 rows), but 'df' currently holds 'arxiv_data.csv' data (51774 rows).
# To align them, we'll re-load the 'news.csv' into 'df' to ensure consistency for this operation.
import pandas as pd

df = pd.read_csv('/content/news.csv')
# Assuming 'News' column is present in news.csv and was used to create 'W'

df['Topic'] = W.argmax(axis=1)
df[['News', 'Topic']].head()

                               News  Topic
0     Virat scored century in match      2
1              BJP won in elections      4
2  Bumrah took 5 wickets in a match      1
3  Congress formed state government      0